language: node_js

node_js: "8"

os:
  - linux
  - osx

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
 -   brew install wine mono
 - fi

 jobs:
  include:
    - stage: Compile The Application
      script: yarn dist
