language: node_js
node_js: "8"

os: "osx"

branches:
  only:
    - master

before_install:
  - brew update
  - brew install wine mono
  - "export DISPLAY=:99.0"
  
script:
- yarn compile
- yarn test
- yarn dist

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
