language: node_js

node_js:
  - '8'
#  - '10' ##################

branches:
  only:
    - master

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

jobs:
 include:
   - stage: Compile Application
     script: npm run dist
   - stage: Test Application
     script: npm test
   - stage: Release Application To GitHub
     script: skip
     before_deploy:
       - git config --local user.name "Oscar Beaumont"
       - git config --local user.email "oscartbeaumont@gmail.com"
       - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
     deploy:
       provider: releases
       api_key: $GITHUB_OAUTH_TOKEN
       file:
         - dist/Netflix-*.dmg
         #- dist/Netflix-*.dmg


         ########
         ########
       file_glob: true
       skip_cleanup: true
       on:
         branch: master

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
