language: node_js
node_js: "8"

os: "osx"

branches:
  only:
    - master

before_install:
  - brew update
  - brew cask install xquartz
  - brew install wine mono
  
script:
- yarn dist
- yarn test

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
